---
language: ruby
sudo: false
env:
  - PUPPET_GEM_VERSION="~> 4.1.0"
  - PUPPET_GEM_VERSION="~> 4.2.0"
  - PUPPET_GEM_VERSION="~> 4.3.0"
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
script: bundle exec rake lint syntax validate spec
